config:
  info: master branch  version-1 

spring:
  datasource:
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: org.gjt.mm.mysql.Driver
     url: jdbc:mysql://localhost:3306/myDB8081?useUnicode=true&characterEncoding=utf-8
     username: root
     password: root

  druid:
         # 指明是否在从池中取出连接前进行检验,如果检验失败, 则从池中去除连接并尝试取出另一个，
         #注意: 设置为true后如果要生效,validationQuery参数必须设置为非空字符串
         test-on-borrow: false
         # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
         #注意: 设置为true后如果要生效,validationQuery参数必须设置为非空字符串
         test-while-idle: true
         # 指明是否在归还到池中前进行检验，注意: 设置为true后如果要生效,
         #validationQuery参数必须设置为非空字符串
         test-on-return: false
         # SQL查询,用来验证从连接池取出的连接,在将连接返回给调用者之前.
         #如果指定,则查询必须是一个SQL SELECT并且必须返回至少一行记录
         validation-query: select 1



myBatis:
 mapperlocations: classpath:com/anhui/springCloud/mapper/**/sql/*.xml
 type-aliases-package: com.anhui.springCloud.model.*

